### PR TITLE
Fix for flexibility in provided states raster

### PR DESCRIPTION
**Pull request by crvernon**
**Purpose:**
States rasters were assumed to have a nodata value of 126 which gets filled by 0 upon converting the substation vector data to a raster using the states raster as a template.  However, if a valid value were to be 126, it would get nullified.  This fix modifies the nodata value in the template states raster to `-np.nan` to ensure that no real value will be masked when filling with 0.  

**Additional:**
- The code was looking for a key that no longer exists when building the `_rval_` variable.  The key was updated to reflect variable name changes that had happened previously.  
- Added raising an error if the `min_volt` field is missing in the provided substation data

### CODE REVIEW

**Review by kmongird — APPROVED** [review]
Looks good!

**Comment by kmongird** [comment]
Only thing I just thought of is if we want to add something about having "min_volt" in the documentation

**Comment by crvernon** [comment]
> Only thing I just thought of is if we want to add something about having "min_volt" in the documentation

agreed.  let me see where that would go.

**Comment by crvernon** [comment]
alright @kmongird docs are updated

**Pull request merged**
